# Site
title: Ahmad Assaf's Blog
description: Ahmad Assaf's blog about Software Engineering, Data Science, Productivity and Web Development
url: http://ahmadassaf.com
github-repo: https://github.com/ahmadassaf/blog/
logo: logo.svg
locale: en_USf

default-post-image: website-screenshot.png   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /posts/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false

# Google Analytics
google-analytics: UA-11075253-1

# Social Links
google       : AhmadAssafA
twitter      : ahmadaassaf
facebook     : ahmad.a.assaf
github       : ahmadassaf
stackoverflow: 557821/ahmadassaf
linkedin     : ahmadassaf
hackernews   : ahmadassaf

featured: []

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    tag: '/:name/'
    category: '/:name/'

# Comments
comments: disqus
disqus:
  shortname: ahmadassaf


# posts-list pagination
paginate: 7
paginate_path: "posts/page/:num"

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

# Gems/plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-archives
  - jekyll-paginate
  - jekyll-time-to-read

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store, node_modules]